//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string lbl_confirm_pass {
            get {
                return ResourceManager.GetString("lbl_confirm_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string lbl_dn
        {
            get {
                return ResourceManager.GetString("lbl_dn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        public static string lbl_dob
        {
            get {
                return ResourceManager.GetString("lbl_dob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frist Name.
        /// </summary>
        public static string lbl_fn
        {
            get {
                return ResourceManager.GetString("lbl_fn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string lbl_gender
        {
            get {
                return ResourceManager.GetString("lbl_gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string lbl_ln
        {
            get {
                return ResourceManager.GetString("lbl_ln", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Adress.
        /// </summary>
        public static string lbl_mail
        {
            get {
                return ResourceManager.GetString("lbl_mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PassWord.
        /// </summary>
        public static string lbl_pass
        {
            get {
                return ResourceManager.GetString("lbl_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Age Must be equal or over 18 years.
        /// </summary>
        public static string Validation_birthdate
        {
            get {
                return ResourceManager.GetString("Validation_birthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password Are Not Matched.
        /// </summary>
        public static string Validation_Confirmpass
        {
            get {
                return ResourceManager.GetString("Validation_Confirmpass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, Enter a valid mail &apos;yourName@Example.com&apos;.
        /// </summary>
        public static string Validation_invalid_mail
        {
            get {
                return ResourceManager.GetString("Validation_invalid_mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PassWord must contains at least One digit, One lowerCase character, One UpperCase character, one special symbols in the list &quot;@#$%&quot; and must be from 6 to 20 characters.
        /// </summary>
        public static string Validation_invalid_pass
        {
            get {
                return ResourceManager.GetString("Validation_invalid_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The max length of this filed is 100.
        /// </summary>
        public static string Validation_maxlength
        {
            get {
                return ResourceManager.GetString("Validation_maxlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Field is Requried.
        /// </summary>
        public static string Validation_reqired
        {
            get {
                return ResourceManager.GetString("Validation_reqired", resourceCulture);
            }
        }
    }
}
